### ISSUE TITLE
Documentation: Location of TF.exe for Visual Studio 2017 install

### ISSUE THREAD

**Issue by stephen-nba** [Microsoft/vsts-vscode#269] opened 2017-06-28 23:18 UTC
The documentation currently states:

"If you plan to use the TFVC command line provided by the Visual Studio IDE, the value to provide will be similar to C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\TF.exe"

Which is for Visual Studio 2015. I have Visual Studio 2017, and the location is actually

"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\TF.exe"

Which is quite different. Maybe the documentation could include help for Visual Studio 2017 as well?

**Comment by dsolodow** [comment] 2017-06-29 01:30
Part of the issue is that the path to tf.exe isn't consistent; it varies based on version and edition of Visual Studio.

However, I may have a good solution. :)
When you install Visual Studio, it creates a Start Menu shortcut called "**Developer Command Prompt for VS YEAR**" where YEAR is 2015, 2017, etc. 
If you launch that, and then at that prompt run ```where tf.exe``` it will give you the full path to it that you can then put into the settings.json.

**Comment by stephen-nba** [comment] 2017-06-29 01:42
I just gave it a go and it worked well.

You could list all the possible locations for each version and edition but it would soon get out of date, so this would be a better tip to include in the documentation.

**Comment by jeffyoung** [comment] 2017-07-06 14:54
Resolved in 1.119.1 (I updated the TFVC README file with this information).

**Closed by jeffyoung** 2017-07-06 14:54 UTC
