### ISSUE TITLE
VSTS does not prompt signin when opening a TFVC folder

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/vsts-vscode#173] opened 2017-04-13 11:41 UTC
It seems that VSTS is not able to recognize my TFVC folder as part of a repository.
VSTS version 1.116.0
VS Code Insider last build.

**Comment by TechWatching** [comment] 2017-04-13 11:43
When I try to signin I have the following error : no team services or team foundation server  repository configuration was found

**Comment by jeffyoung** [comment] 2017-04-13 15:44
Hi @TechWatching.  Thanks for trying out the TFVC support!  This is typically an issue when the extension doesn't detect a repository in that folder (for some reason).  We'll just need to figure out what the reason is.  😄 

In the other thread, #58, you mentioned you were on a PC.  Can you tell me which TF client you set up via the `tfvc.location` setting (tf.exe or the TEE CLC)?  And did you place that setting in your User settings or Workspace settings?  If that is set up properly, I'd be interesting in seeing the output from the tf workfold command run in that folder.  That's the command that is run to determine the state of the workspace in the opened folder (the extension parses the output from that command for various bits of information used to connect).

Finally, if you could [enable logging](https://github.com/Microsoft/vsts-vscode#logging), re-start VS Code and open the same folder then provide the contents of that log, that would help.

**Comment by TechWatching** [comment] 2017-04-14 11:23
Thanks for your answer. 
I set up my tfvc.location using tf.exe (C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\TF.exe). I place that setting in User settings. 
I have the following error with the log : TFVC errors: TF30063: You are not authorized to access ******\DefaultCollection. 
I guess it might be a proxy error, I have seen there is a setting for that to but I don't know what exactly is a tfs proxy server and what I should put.

**Comment by jeffyoung** [comment] 2017-04-14 14:55
Hi @TechWatching, is there any way you could provide more of the log (and certainly remove any specifics)?  I'm curious to know if your server is local (on-premises) or a perhaps hosted implementation of Team Foundation Server (that is, hosted by a service provider).  I'd also like to know if the server is set up for HTTPS (which we need to debug as we've got several issues with the extension, #59 being one).

**Comment by TechWatching** [comment] 2017-04-18 11:19
Sorry with the week-end and the bank holiday I have not been able to provide you more info sooner. 
I have no idea if the server is set up for HTTPS. As far as I know it is a TFS 2015 onpremise. You can find in the file herewith the log.
[team-extension2.txt](https://github.com/Microsoft/vsts-vscode/files/928872/team-extension2.txt)

**Comment by jeffyoung** [comment] 2017-04-18 15:23
OK, thanks for the information. I presume you edited this line `TFVC errors: TF30063: You are not authorized to access ******\DefaultCollection` and removed the server information?  That's what would tell us if you're using HTTPS or not.

Regardless, can you open a command prompt and run the same command?  Essentially, `tf.exe workfold d:\TFS\Workspace_2`.  I'm curious if that will work (which is what the VS Code extension runs).  If it does, can you then try to re-open the same folder in VS Code?

**Comment by TechWatching** [comment] 2017-04-24 10:39
Ah okay, then it's not https as there is no https in the server informationI removed.

Running this command in command line outputs : 
Collection : *********/tfs/defaultcollection 
$/: D: \TFS\Workspace_2

So what is strange is that the command seams to work with the command line but not through VS Code.

**Comment by jeffyoung** [comment] 2017-04-25 15:00
It's certainly a bit odd that it would work in the command line but not through VS Code (since the VS Code extension calls the command line; although it uses the credentials you provided when you signed in via the extension).

Can you ensure you've updated the extension to 1.117.0 and give it another shot?  We had a permissions issue (#172) previously that I made a fix for (although I don't think it was for a TF30063 error).

I also notice that you've mapped the entire team project collection via $/ in your workspace.  Do you know how many team projects you have in your team project collection?  Either way, we use the workspace information to try and determine what the team project is.  If you only map $/ we might not be able to determine the team project to use.  If your workspace were to map $/TeamProject1, then we know that the team project is TeamProject1.  So perhaps you can provide a bit more detail on what your set up is like?

**Comment by TechWatching** [comment] 2017-04-26 11:47
When you say "credentials you provided when you signed in via the extension", what are you talking about ? Because actually when I open the folder on vs code, nothing happen, vs code does not recognize this folder is mapped to a tfs project : when I type the signin command I have the following message : "(team) No Team Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder that contains a repository."

Indeed I have several projects in my team project collection but I have only one in local mapped. I gave it a try but it didn't work either when I try from a folder inside my Team Project. I don't know what other information I could give you. Do you think it could be linked to my proxy or something like that ?

**Comment by jeffyoung** [comment] 2017-04-27 18:37
So what I'm referring to is the behavior that will happen when you open a folder to a _local_ TFVC workspace.  We detect one by a successful run of `tf workfold` and then can query the server for the proper project collection and team project information.  All of that information is then used to communicate back to the server.

However, I'm starting to think that this is the same situation as #185 and #176.

Since you can run `tf workfold` from `d:\TFS\Workspace_2` successfully, can you also run tf workspace from the same location? When you do, a dialog like the one below will show up and I'd like to know the value of `Location`.

![image](https://cloud.githubusercontent.com/assets/2796865/25498644/d32b2206-2b56-11e7-8b9b-d24a86158f3c.png)

I'm going to see if I can detect server workspaces and make it apparent (in the UI somehow) that a _local_ workspace is necessary.  However, I'd still like to know if that's the case for you.

**Comment by TechWatching** [comment] 2017-04-28 11:45
You are right : location is "Server" on  my dialog.

**Comment by jeffyoung** [comment] 2017-04-28 13:40
Great, thanks! The workaround at this point is to change it to a local workspace.  Here's [some documentation](https://www.visualstudio.com/en-us/docs/tfvc/decide-between-using-local-server-workspace) on the differences between server and local workspaces.

(Duplicate of #176)

**Closed by jeffyoung** 2017-04-28 13:40 UTC
Labels: duplicate

**Comment by florinvirdol** [comment] 2018-10-03 13:58
> [team-extension.log](https://github.com/Microsoft/vsts-vscode/files/1908466/team-extension.log)
> 
> @jeffyoung I have same error as discussed in this thread and my Location is also local not Server on tf workspace dialog. I have tried everything could not get it fixed.

I was getting the same error, but it worked after i put the `tf.exe` full path into my `TFVC.Location` VsCode Settings:  
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe`

_Open VsCode -> File -> Preferences -> Settings -> Search `tfvc` inside the "Search settings" input -> Add the full path to that `Tfvc:Location` option_
