### ISSUE TITLE
Non-default projects use default project URLs

### ISSUE THREAD

**Issue by DustinVenegas** [Microsoft/vsts-vscode#25] opened 2016-07-25 06:22 UTC
I have multiple team projects in VSTS. When I load them in VSCode with the extension enabled the URL links appear to be incorrect. 

For example, "View Your Team Project Website" points to "https://mainorg.visualstudio.com/mainorg/Sub-Project" instead of "https://mainorg.visualstudio.com/Sub-Project". 

All of the URL relating to this plugin have the same issue.

**Comment by jeffyoung** [comment] 2016-07-25 18:42
Hi Dustin.  Thanks for giving the extension a try!

This sounds like issue #24 that I sent a private fix for (I'll be testing it out soon for a pull request).  As I did in the other issue, could I ask you to turn on the logging, repro the issue and send the log file to me at jeyou at microsoft dot com? I'd like to take a look and see if it's the same issue or not.

**Comment by DustinVenegas** [comment] 2016-07-26 22:32
Thanks for the heads up @jeffyoung. I provided the logs and this does appear to be a duplicate of #24. If you need another person to test the fix I'll be glad to do so. If not, there's no rush and I can wait until the next release. 

Thank you again for the extension and your timely assistance!

**Comment by jeffyoung** [comment] 2016-08-02 14:56
Closing as a duplicate of #24.  Should be fixed in 104 release.

**Closed by jeffyoung** 2016-08-02 14:56 UTC
Labels: duplicate
