### ISSUE TITLE
The associate work item, not populating commit message

### ISSUE THREAD

**Issue by MilesHart** [Microsoft/vsts-vscode#341] opened 2017-11-14 12:03 UTC
The youtube tute shows how to associate a work item, but this doesn't seem to work.

https://youtu.be/sk6LrzQX4P8?t=5m53s

The commit message remains blank.

**Comment by MilesHart** [comment] 2017-11-14 12:56
If you manually add the "#{bug item}" then this works as prescribed.

**Comment by dougrday** [comment] 2017-11-30 18:03
Duplicate of #314

**Comment by kaylangan** [comment] 2017-12-04 20:03
This is a duplicate of #314

**Closed by kaylangan** 2017-12-04 20:03 UTC
