### ISSUE TITLE
Unable to find the TF executable

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vsts-vscode#295] opened 2017-07-31 19:25 UTC
OS: MacOS Sierra
VS Code: 1.14.2
VSTS Plugin Version: current as of 2017-07-31
TF: Team Explorer Everywhere Command Line Client (version 14.120.0.201706271643)

Tried opening VS Code on a directory I checked out via the Eclipse plugin, and getting the following error:

`(team) Unable to find the TF executable. Please ensure TF is installed and the path specified contains the filename. Provided path: /usr/local/bin/tf`

TF is installed at that location...

```
$ which tf
/usr/local/bin/tf
```

I installed via `brew install tee-clc`

**Comment by jeffyoung** [comment] 2017-08-10 15:29
Hi @tracker1, thanks for trying out the extension.

I was able to reproduce this when installing with brew (admittedly, I've never installed it that way... I've always just extracted the zip from the [GitHub releases](https://github.com/Microsoft/team-explorer-everywhere/releases)).  I'll need to investigate but installing from GH releases might be a workaround.

**Comment by tracker1** [comment] 2017-08-10 20:48
@jeffyoung may try that... I was just trying what seemed like the most straight forward approach.

**Comment by jeffyoung** [comment] 2017-08-14 17:35
Thanks @tracker1.  I've got a PR out where I've updated the code to also check for symlinks for tf.  The code that was failing was attempting to ensure that it was a file (and thus failed).  The next release (due out soon) will contain the fix for that.  That said, I don't think our team actually releases via Homebrew but I appreciate you reporting the issue.

**Comment by jeffyoung** [comment] 2017-08-14 19:40
I just released v1.122.0 that has a fix for this.  Please reopen if you don't see it working as intended.  Thanks!

**Closed by jeffyoung** 2017-08-14 19:40 UTC
Labels: bug

**Comment by tracker1** [comment] 2017-08-14 22:18
@jeffyoung I'm pretty sure the brew recipe just grabs the release archive and sets it up under the appropriate homebrew file structure with symlinks.

Thanks for addressing this issue.

**Comment by AppleEducate** [comment] 2018-06-21 15:01
For those wondering like myself, if you install via home-brew the path was this for me: 
`/usr/local/Cellar/tee-clc/14.134.0/libexec/tf`
