### ISSUE TITLE
(Team)Unable to store credentials for this Host:

### ISSUE THREAD

**Issue by bayarmohamed** [Microsoft/vsts-vscode#396] opened 2018-05-08 12:25 UTC
I m on windows 10 machine and I got this issue :
![image](https://user-images.githubusercontent.com/39089184/39756981-e4078484-52ba-11e8-9255-fa83364be194.png)
Any help please???

**Comment by kaylangan** [comment] 2018-05-08 16:57
Closing as duplicate of #62

**Closed by kaylangan** 2018-05-08 16:57 UTC
