### ISSUE TITLE
Workspace not detected? Cannot select SCM Provider

### ISSUE THREAD

**Issue by Rainson12** [Microsoft/vsts-vscode#217] opened 2017-05-05 09:24 UTC
Hey,
were running TFS on Premise using TFS 2015 Update 3. My Workspace is created using VS 2017 and the location is set to local. The mapping of the project is "$/Mobile/Apps/SysmexSupport: C:\Develop\SysmexSupport" according to `tf.exe workspaces /format:detailed /collection:"http://ourserver:8080/tfs/mordor/`. When opening the local folder in vscode it only allows me to add the project to a git repository for what ever reason it does not detect the tfs connection. In my user Settings i have set 

`"tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\TF.exe"`

In my workspace settings i have set 
`    "team.remoteUrl": "http://ourserver:8080/tfs/Mordor/",
    "team.teamProject": "Mobile"`

**Comment by NavBitsAndBytes** [comment] 2017-05-05 15:49
Same issue appears to be plaguing me as well.

**Comment by jeffyoung** [comment] 2017-05-05 17:59
Thank you both for trying out the extension (@Rainson12 and @NavBitsAndBytes).

Could each you [enable logging](https://github.com/Microsoft/vsts-vscode#logging) and provide the results?  Also, you should _not_ set either `team.remoteUrl` or `team.teamProject` as those are provided for the scenario when your source code is not hosted in TFS/TS but your work items and builds are. That information is to be picked up from your tfvc workspace (although if that isn't working, I can see why you might set them; however, it won't make it easier to debug the original issue).

**Comment by Rainson12** [comment] 2017-05-08 08:14
this is what i get
`2017-05-08T08:13:40.343Z - info:   [13588] *** FOLDER: c:\Develop\API Server Base ***
2017-05-08T08:13:40.348Z - info:   [13588] version 1.117.3
2017-05-08T08:13:40.349Z - debug:  [13588] Looking for an External Context at c:\Develop\API Server Base
2017-05-08T08:13:40.350Z - debug:  [13588] No External Context at c:\Develop\API Server Base
2017-05-08T08:13:40.355Z - debug:  [13588] Looking for TFVC repository at c:\Develop\API Server Base
2017-05-08T08:13:40.356Z - debug:  [13588] TFVC Creating Tfvc object with localPath='undefined'
2017-05-08T08:13:40.356Z - debug:  [13588] Using TFS proxy: undefined
2017-05-08T08:13:40.356Z - debug:  [13588] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2017-05-08T08:13:40.357Z - debug:  [13588] TFVC Repository created with repositoryRootFolder='c:\Develop\API Server Base'
2017-05-08T08:13:40.358Z - debug:  [13588] TFVC Repository.CheckVersion
2017-05-08T08:13:40.359Z - debug:  [13588] TFVC: tf add -noprompt -?
2017-05-08T08:13:40.376Z - debug:  [13588] TFVC: spawned new process (duration: 16ms)
2017-05-08T08:13:40.389Z - debug:  [13588] TFVC: spawned new process (duration: 12ms)
2017-05-08T08:13:40.629Z - debug:  [13588] TFVC: add exit code: 0 (duration: 269ms)
2017-05-08T08:13:40.632Z - debug:  [13588] TFVC Repository.FindWorkspace with localPath='c:\Develop\API Server Base'
2017-05-08T08:13:40.633Z - debug:  [13588] TFVC: tf workfold -noprompt ********
2017-05-08T08:13:40.641Z - debug:  [13588] TFVC: spawned new process (duration: 7ms)
2017-05-08T08:13:40.971Z - debug:  [13588] TFVC: workfold exit code: 0 (duration: 337ms)
2017-05-08T08:13:40.973Z - error:  [13588] It appears you have configured a non-English version of the TF executable. Please ensure an English version is properly configured.`

**Comment by Rainson12** [comment] 2017-05-08 09:03
checkin still doesnt work as somehow the extensions assumes that the project is the tfs team project "API Server" instead of "Mobile". How can i change this? Setting  "team.teamProject": "Mobile" didnt work.

**Comment by jeffyoung** [comment] 2017-05-10 18:38
Hi @Rainson12

So the first issue is actually by design (the .NET Framework design, that is). Your system must be set to show you German UI and that's why tf.exe is looking for resources under that "de" folder.  When you rename it, you prevent tf.exe from finding those German resources and it falls back to the English strings compiled into the executable.  There's no way to tell tf.exe to return all output in English (at the command line) so we do our best to indicate what the problem is and try to offer guidance on how to fix it. So whenever you install VS on a system, it will install those language packs and they will be picked up automatically. (Looking on my English only system, it appears there are at least 14 different language packs installed in that Team Explorer folder. At some point, the Visual Studio guys must have decided to install all of the language packs by default. They used to be optional.)

Regarding the second issue, this is #179. The default behavior of the extension is to expect that a workspace is mapped to a single, particular team project. If more than one team project is mapped, the first one found is used (we parse the output of the `tf workfold` command). The feature I call ["Restrict Workspace"](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#restricting-status-changes-to-the-current-vs-code-workspace) was introduced in 1.117.0 which allows you to restrict the workspace shown by the TFVC Viewlet to only the folder opened within Visual Studio Code. You should try that out and see if it satisfies your requirements.

Regarding the work items policy, thanks for confirming that using the CLC works for you. It's unfortunate but it's (another) bug in tf.exe.

Lastly, you shouldn't need to keep the `team.remoteUrl` and `team.teamProject` settings set. They're meant for users who have their source code outside of either TFS or Team Services but whose Build and Work Items _are_ on TFS or Team Services. More details [here](
https://github.com/Microsoft/vsts-vscode#using-external-non-microsoft-source-repositories). Having those set can definitely provide confusing results.

I'll close this issue now but if you run into anything else, feel free to open a new one.

**Closed by jeffyoung** 2017-05-10 18:38 UTC
