### ISSUE TITLE
TFVC (tf.exe) Can't link check-ins with the associated work item

### ISSUE THREAD

**Issue by Rackmire** [Microsoft/vsts-vscode#361] opened 2018-01-23 09:51 UTC
I'm using VSTS online, VS Code (1.19.2), and using tf.exe from Visual Studio Community Ed. 2017.

I'm able to connect to the TFVC / workspace and check-in with an associated work item in the following format i.e #{itemID} - {Work Item Name}, but when it then goes into VSTS and I check the changeset, the Work item isn't linkable and it isn't associated with the work item. There's no link/history/changeset present.

I'm not sure if this is a known bug or a feature request. 

Thanks,

**Comment by dougrday** [comment] 2018-02-07 22:21
Possible duplicate of #314

**Comment by kaylangan** [comment] 2018-03-13 20:08
Closing as dupe of #314.

**Closed by kaylangan** 2018-03-13 20:08 UTC
Labels: duplicate
